# Generated by Django 5.1.6 on 2025-02-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='valor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
