# Generated by Django 5.1.6 on 2025-02-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alimentos_valor_alter_alimentos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
