# Generated by Django 5.1.6 on 2025-02-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_alimentos_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='preciokg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
