# Generated by Django 5.1.6 on 2025-02-27 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alimentos_preciokg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicios', models.CharField(blank=True, max_length=255)),
                ('tipo_servicios', models.CharField(blank=True, max_length=255)),
                ('costo_servicios', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_servicios', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_transporte', models.CharField(blank=True, choices=[('Gas', 'Gas'), ('Combustible', 'Combustible'), ('Pasaje', 'Pasaje')], max_length=20)),
                ('tipo_transporte', models.CharField(blank=True, max_length=255)),
                ('cantidad_transporte', models.CharField(blank=True, max_length=255)),
                ('costo_transporte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_transporte', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='alimentos',
            old_name='preciokg',
            new_name='preciokg_alimentos',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='valor',
        ),
        migrations.AddField(
            model_name='alimentos',
            name='cantidad_alimentos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='costo_alimentos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='fecha_alimentos',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentos',
            name='producto_alimentos',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
