# Generated by Django 5.1.6 on 2025-02-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_servicios_transporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='preciokg_alimentos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
